export const AUTOMATED_METRIC_FALLBACKS = {
  bettingOdds: {
    available: false,
    provider: "",
    observedAt: "",
    expiresAt: "",
    markets: [],
    evidencePolicy: {
      sourceClass: "commercial-market-snapshot",
      priceType: "",
      probabilityMethod: "",
      predictiveClaim: false,
      secondaryFallbackAllowed: false,
    },
  },
  electionPolling: {
    available: false,
    latestPublicationDate: "",
    expiresAt: "",
    polls: [],
    aggregation: { method: "none", explanation: "" },
    evidencePolicy: {
      sourceClass: "primary-pollster-publication",
      bpcDisclosureRequired: true,
      secondaryAggregatorsUsedAsData: false,
    },
  },
  employmentStats: {
    available: false,
    headline: {
      period: "",
      observedAt: 0,
      releaseDate: "",
      employmentRate: 0,
      unemploymentRate: 0,
      inactivityRate: 0,
      vacancies: 0,
      vacanciesPeriod: "",
    },
    methodology: { status: "", caveat: "" },
    source: { bulletinUrl: "", landingUrl: "" },
  },
  gdpTracker: {
    available: false,
    headline: {
      period: "",
      observedAt: 0,
      releaseDate: "",
      monthlyGrowth: 0,
      threeMonthGrowth: 0,
    },
    methodology: { measure: "", status: "", revisionNote: "" },
    source: { bulletinUrl: "", landingUrl: "" },
  },
  migrationStats: {
    headline: {
      period: "",
      observedAt: 0,
      releaseDate: "",
      netMigration: 0,
      immigration: 0,
      emigration: 0,
      previousPeriod: "",
      previousNetMigration: 0,
      changePercent: 0,
      provisional: true,
    },
    comparison: [],
    methodology: {
      definition: "",
      status: "",
      revisionNote: "",
    },
    source: {
      edition: "",
      bulletinUrl: "",
      datasetUrl: "",
    },
  },
  nationalDebt: {
    baseDebt: 0,
    baseDate: 0,
    debtToGdp: 0,
    observationPeriod: "",
    publicationDate: "",
    revisionStatus: "",
    source: {
      publisher: "",
      debtUrl: "",
      debtToGdpUrl: "",
    },
    series: {
      debt: "",
      debtToGdp: "",
    },
  },
  nhsStats: {
    available: false,
    expiresAt: "",
    headline: {
      period: "",
      observedAt: 0,
      publicationDate: "",
      waitingPathwaysEstimate: 0,
      waitingPathwaysDisplay: "",
      uniquePatientsEstimate: 0,
      within18WeeksPercent: 0,
      standardPercent: 92,
      medianWaitWeeks: 0,
      percentile92WaitWeeks: 0,
      over52Weeks: 0,
      over65Weeks: 0,
      over78Weeks: 0,
      over104Weeks: 0,
      yearChangePercent: 0,
      yearChangePathways: 0,
      newPathways: 0,
      admittedCompleted: 0,
      nonAdmittedCompleted: 0,
    },
    specialties: [],
    missingTrusts: [],
    methodology: {
      geography: "",
      measure: "",
      waitingListUnit: "",
      peopleCaveat: "",
      estimatesCaveat: "",
      revisionNote: "",
    },
    source: {
      publisher: "",
      landingUrl: "",
      dataPageUrl: "",
      pressNoticeUrl: "",
    },
    evidencePolicy: {
      sourceClass: "official-primary",
      headlineIncludesMissingTrustEstimates: true,
      specialtiesIncludeMissingTrustEstimates: false,
      withdrawnSeries: [],
    },
  },
  sentimentPulse: {
    available: false,
    order: [],
    series: {},
    methodology: {
      alignment: "",
      evidenceClass: "official-data",
    },
  },
  taxRevenue: {
    available: false,
    headline: {
      period: "",
      observedAt: 0,
      releaseDate: "",
      receiptsBillion: 0,
      yearChangeBillion: 0,
    },
    methodology: { measure: "", status: "", caveat: "" },
    source: { bulletinUrl: "", landingUrl: "" },
  },
  crimeStatistics: {
    available: false,
    headline: {
      publisher: "",
      publicationTitle: "",
      publicationUrl: "",
      period: "",
      observedAt: "",
      releaseDate: "",
      nextReleaseDate: "",
      geography: "",
    },
    crimeSurvey: { status: "unavailable", measures: [] },
    policeRecorded: { status: "unavailable", measures: [] },
    justice: { status: "unavailable", measures: [] },
    regional: {
      status: "unavailable",
      title: "Regional comparisons",
      reason: "",
    },
    evidencePolicy: {
      combinedTotalAllowed: false,
      modulesValidatedIndependently: true,
      regionalRankingPublished: false,
    },
  },
} as const;

export type AutomatedMetricSection = keyof typeof AUTOMATED_METRIC_FALLBACKS;

export const AUTOMATED_METRIC_KEYS = Object.keys(
  AUTOMATED_METRIC_FALLBACKS
) as AutomatedMetricSection[];
